#!/usr/bin/python3

def raise_exception_msg(msg=""):
    """Raise the NameError exception with a message"""

    raise NameError(msg)
